[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.94.1"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
# workspace
bench-core = { path = "crates/bench-core" }
txgen-core = { path = "crates/txgen-core" }
txgen-ethereum = { path = "crates/txgen-ethereum" }
txgen-tempo = { path = "crates/txgen-tempo" }
txgen-cli = { path = "crates/txgen-cli" }
txgen-property = { path = "crates/txgen-property" }

# CLI
clap = { version = "4", features = ["derive"] }

# serde
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"

# alloy
alloy-primitives = { version = "1", features = ["rand", "serde"] }
alloy-dyn-abi = { version = "1", features = ["eip712"] }
alloy-json-abi = "1"
alloy-signer = "2"
alloy-signer-local = "2"
alloy-consensus = { version = "2", features = ["k256"] }
alloy-network = "2"
alloy-provider = { version = "2", features = ["debug-api", "engine-api", "ws"] }
alloy-reth = "0.2"
alloy-rpc-types-eth = "2"
alloy-eips = "2"
alloy-rlp = "0.3"
alloy-sol-types = "1"

# tempo
tempo-alloy = "1"
tempo-primitives = "1"

# crypto
aes-gcm = "0.10"
hkdf = "0.12"
k256 = { version = "0.13", features = ["ecdh"] }
sha2 = "0.10"

# misc
futures = "0.3"
hex = "0.4"
rand = "0.9"
rayon = "1"
rustix = { version = "1", features = ["fs"] }
eyre = "0.6"
tokio = "1"
uuid = { version = "1", features = ["v4", "serde"] }
zeroize = "1"
abi-fuzz = { git = "https://github.com/tempoxyz/abi-fuzz", rev = "2d8dac35d70fa13072f183ea8c9a90d144e3144f" }
reqwest = { version = "0.13", features = ["json"] }
