[package]
name = "txgen-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
# serde
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-dyn-abi.workspace = true
alloy-json-abi.workspace = true
alloy-signer.workspace = true
alloy-signer-local = { workspace = true, features = ["mnemonic", "secp256k1"] }

# misc
rand.workspace = true
rayon.workspace = true
eyre.workspace = true
hex.workspace = true
