[package]
name = "txgen-ethereum"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "txgen-ethereum"
path = "src/bin/main.rs"

[dependencies]
# workspace
txgen-core.workspace = true
txgen-cli.workspace = true

# async
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }

# serde
serde.workspace = true
serde_yaml.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-signer.workspace = true
alloy-network.workspace = true
alloy-provider.workspace = true

# misc
rand.workspace = true
eyre.workspace = true
