[package]
name = "bench-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
# workspace
txgen-core.workspace = true

# serde
serde.workspace = true
serde_json.workspace = true

# alloy
alloy-primitives.workspace = true

# async
tokio = { version = "1", features = ["rt", "sync", "time", "process", "io-util", "io-std"] }
futures = "0.3"

# http
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }

# misc
hex.workspace = true
eyre.workspace = true
thiserror.workspace = true
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
