[package]
name = "bench-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
# workspace
txgen-core.workspace = true

# serde
serde.workspace = true
serde_json.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-network.workspace = true
alloy-provider.workspace = true
alloy-transport = "2"
alloy-eips.workspace = true

# async
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync", "time", "io-util", "io-std"] }

# http
reqwest = { version = "0.13", default-features = false, features = ["rustls", "json"] }

# misc
futures.workspace = true
rand.workspace = true
eyre.workspace = true
hex.workspace = true
tracing = "0.1"
urlencoding = "2"
uuid.workspace = true
prometheus_remote_write = { version = "0.2", features = ["compression"] }
flate2 = "1"

[dev-dependencies]
alloy-rpc-client = "2"
prost = "0.12"
snap = "1"
tempfile = "3"
tokio = { version = "1", features = ["rt", "macros"] }
