[package]
name = "txgen-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
# workspace
txgen-core.workspace = true

# CLI
clap = { version = "4", features = ["derive"] }

# serde
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true

# misc
rand.workspace = true
eyre.workspace = true

# alloy
alloy-provider.workspace = true
alloy-dyn-abi.workspace = true
alloy-primitives.workspace = true
alloy-consensus.workspace = true
alloy-network.workspace = true
alloy-signer.workspace = true
alloy-eips.workspace = true
alloy-rlp.workspace = true
alloy-rpc-types-engine = "2"
hex.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "rt", "sync", "time"] }
