name: Build Docker image

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io/tempoxyz

jobs:
  build-and-push:
    name: build and push docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Secure runner
        uses: tempoxyz/gh-actions/actions/secure-runner@bce53819ffa60fcdf8f0f349686d807e5a66a71b # 2026-09-21T21-56-41Z-bce53819

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - id: shortsha
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: echo "shortsha=$(echo "$GITHUB_SHA" | cut -c1-7)" >> "$GITHUB_OUTPUT"

      - name: Set up Docker Buildx
        uses: tempoxyz/gh-actions/vendor/docker/setup-buildx-action@bce53819ffa60fcdf8f0f349686d807e5a66a71b # 2026-09-21T21-56-41Z-bce53819

      - name: Log in to Container Registry
        uses: tempoxyz/gh-actions/vendor/docker/login-action@bce53819ffa60fcdf8f0f349686d807e5a66a71b # 2026-09-21T21-56-41Z-bce53819
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: tempoxyz/gh-actions/vendor/docker/build-push-action@bce53819ffa60fcdf8f0f349686d807e5a66a71b # 2026-09-21T21-56-41Z-bce53819
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/txgen:${{ steps.shortsha.outputs.shortsha }},${{ env.REGISTRY }}/txgen:latest
          cache-from: type=gha
          cache-to: type=gha,mode=full
