name: Scan GitHub Actions

"on":
  pull_request:

permissions: {}

jobs:
  scan:
    name: Scan GitHub Actions
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@0a60d757d0f4725a34f22f7b9ebf7b91b4b00bcf
    permissions:
      actions: read
      contents: read
      id-token: write
